### ISSUE TITLE
Adjust Images in Dark Mode

### ISSUE THREAD

**Issue by FlorianRappl** [smapiot/pidoc#8]
We could add an additional CSS class for images such as `auto`. When used, this class would automatically try to adjust the image's content via the following CSS declaration:

```css
body.dark img.auto {
  filter: invert()hue-rotate(180deg);
}
```
